### ISSUE TITLE
Legacy in GUI developments

### ISSUE THREAD

**Issue by changkun** [faiface/gui#15]
Hi @faiface, thank you so much for writing this inspiring and awesome package.

I read your README and got a few questions:

1. You mentioned that you'd like to get rid of C dependencies, such as `glfw`. I have huge interests in how that could be possibly done. As I partially read your code, the glfw is for cross-platform window, kb/mo events managements, and `gl` is for rendering. To get rid of those C dependencies, on macOS, one must use cocoa and metal for those purposes, and on Linux, X11 and OpenGL seems to be the only way for those purposes. It seems to me that no matter what we do, there must be some C dependencies. Could you maybe share a few of your thoughts on how to get rid of C in Go for doing GUI stuff?
2. You also mentioned that "Due to stupid limitations imposed by operating systems, the internal code that fetches events from the OS must run on the main thread of the program." I learned the constraint from the golang-nuts mailing list but never dig into the historical reason about this. Perhaps you know more about how the limitation was introduced and why is it still exists today? Furthermore, if we get rid of the C dependencies from Go, how could the main thread limitation be improved from here?
 
Thank you very much for your reading and happy new year :)

**Comment by faiface** [comment]
Hi, @changkun, I'm terribly sorry for not replying to your nice message, I must've forgotten about it.

It's probably late, but I'll try and answer your questions.

1. It might actually not be possible, but the idea is that a lot of stuff can be done through syscalls. For example, [Ebiten](https://github.com/hajimehoshi/ebiten) on Windows requires no CGO, Hajime managed to do this. It does require CGO on other platforms, but the fact that he did it for Windows suggests it might be possible on other platforms as well, especially since this library requires much less than Ebiten.
2. Okay, that statement is a tiny bit inaccurate, here's how it truly is: events must be fetched on the same thread that created the window. This is simply because of how the OSs implement the windowing stuff. I think they remember which thread created which window and then distribute events accordingly, but I might be wrong in this explanation. Anyway, it's something along those lines.

Once again, sorry for the late reply and I wish you a happy rest of the year!
